http://localhost:4000/

###
http://localhost:4000/blocks
###

POST http://localhost:3000/blocks


### 
http://localhost:4000/blocks/3

###

POST http://localhost:4000/transactions

{
    "to":"hyunyu",
    "amount":60
}

###
http://localhost:4000/mempool

###
http://localhost:4000/balance/hyunyu

###
http://localhost:4000/wallet

###
POST http://localhost:4000/peers

{
    "address": "127.0.0.1",
    "port": "3000"
}
###

http://localhost:3000/peers


###
http://localhost:3000/status